package com.example.core.network.model

import SuggestAutocompleteAll
import kotlinx.serialization.Serializable

@Serializable
data class Data(

    var id: Int? = null,
    var apiModel: String? = null,
    var apiLink: String? = null,
    var isBoosted: Boolean? = null,
    var title: String? = null,
    var altTitles: String? = null,
    var thumbnail: Thumbnail? = Thumbnail(),
    var mainReferenceNumber: String? = null,
    var hasNotBeenViewedMuch: Boolean? = null,
    var boostRank: String? = null,
    var dateStart: Int? = null,
    var dateEnd: Int? = null,
    var dateDisplay: String? = null,
    var dateQualifierTitle: String? = null,
    var dateQualifierId: Int? = null,
    var artistDisplay: String? = null,
    var placeOfOrigin: String? = null,
    var dimensions: String? = null,
    var mediumDisplay: String? = null,
    var inscriptions: String? = null,
    var creditLine: String? = null,
    var publicationHistory: String? = null,
    var exhibitionHistory: String? = null,
    var provenanceText: String? = null,
    var publishingVerificationLevel: String? = null,
    var internalDepartmentId: Int? = null,
    var fiscalYear: String? = null,
    var fiscalYearDeaccession: String? = null,
    var isPublicDomain: Boolean? = null,
    var isZoomable: Boolean? = null,
    var maxZoomWindowSize: Int? = null,
    var copyrightNotice: String? = null,
    var hasMultimediaResources: Boolean? = null,
    var hasEducationalResources: Boolean? = null,
    var colorfulness: Double? = null,
    var color: Color? = Color(),
    var latitude: String? = null,
    var longitude: String? = null,
    var latlon: String? = null,
    var isOnView: Boolean? = null,
    var onLoanDisplay: String? = null,
    var galleryTitle: String? = null,
    var galleryId: String? = null,
    var artworkTypeTitle: String? = null,
    var artworkTypeId: Int? = null,
    var departmentTitle: String? = null,
    var departmentId: String? = null,
    var artistId: Int? = null,
    var artistTitle: String? = null,
    var altArtistIds: ArrayList<String> = arrayListOf(),
    var artistIds: ArrayList<Int> = arrayListOf(),
    var artistTitles: ArrayList<String> = arrayListOf(),
    var categoryIds: ArrayList<String> = arrayListOf(),
    var categoryTitles: ArrayList<String> = arrayListOf(),
    var artworkCatalogueIds: ArrayList<String> = arrayListOf(),
    var termTitles: ArrayList<String> = arrayListOf(),
    var styleId: String? = null,
    var styleTitle: String? = null,
    var altStyleIds: ArrayList<String> = arrayListOf(),
    var styleIds: ArrayList<String> = arrayListOf(),
    var styleTitles: ArrayList<String> = arrayListOf(),
    var classificationId: String? = null,
    var classificationTitle: String? = null,
    var altClassificationIds: String? = null,
    var classificationIds: ArrayList<String> = arrayListOf(),
    var classificationTitles: ArrayList<String> = arrayListOf(),
    var subjectId: String? = null,
    var altSubjectIds: ArrayList<String> = arrayListOf(),
    var subjectIds: ArrayList<String> = arrayListOf(),
    var subjectTitles: ArrayList<String> = arrayListOf(),
    var materialId: String? = null,
    var altMaterialIds: ArrayList<String> = arrayListOf(),
    var materialIds: ArrayList<String> = arrayListOf(),
    var materialTitles: ArrayList<String> = arrayListOf(),
    var techniqueId: String? = null,
    var altTechniqueIds: ArrayList<String> = arrayListOf(),
    var techniqueIds: ArrayList<String> = arrayListOf(),
    var techniqueTitles: ArrayList<String> = arrayListOf(),
    var themeTitles: ArrayList<String> = arrayListOf(),
    var imageId: String? = null,
    var altImageIds: ArrayList<String> = arrayListOf(),
    var documentIds: ArrayList<String> = arrayListOf(),
    var soundIds: ArrayList<String> = arrayListOf(),
    var videoIds: ArrayList<String> = arrayListOf(),
    var textIds: ArrayList<String> = arrayListOf(),
    var sectionIds: ArrayList<String> = arrayListOf(),
    var sectionTitles: ArrayList<String> = arrayListOf(),
    var siteIds: ArrayList<String> = arrayListOf(),
    var suggestAutocompleteAll: ArrayList<SuggestAutocompleteAll> = arrayListOf(),
    var lastUpdatedSource: String? = null,
    var lastUpdated: String? = null,
    var timestamp: String? = null

)
